include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_literals_to_create_immutables: false

analyzer:
  strong-mode:
    implicit-casts: true

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
