name: farmhub
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  auto_route: ^3.0.4

  # Firebase Suite
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  google_sign_in: ^5.2.1

  # Functional Programming
  fpdart: ^0.0.12

  # Value Equality
  equatable: ^2.0.3
  freezed_annotation:

  # Business Logic and Dependency Injection
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  hydrated_bloc: ^8.0.0
  get_it: ^7.2.0

  # Local Storage
  shared_preferences: ^2.0.13

  # Data and Internet
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.4.0

  # Render
  flutter_svg: ^1.0.0
  simple_animations: ^4.0.1
  bottom_nav_layout: ^3.0.9
  sliver_tools: ^0.2.5
  boxy: ^2.0.5
  syncfusion_flutter_charts: ^19.4.53
  sprung: ^3.0.0
  tab_indicator_styler: ^2.0.0
  flutter_speed_dial:
    git:
      url: git://github.com/nazrinharris/flutter_speed_dial.git
      ref: master
  #flutter_speed_dial:
  #  path: ./packages/flutter_speed_dial-5.0.0+1-modified

  # Misc
  lint: ^1.8.1
  logger: ^1.1.0
  path_provider: ^2.0.8
  intl: ^0.17.0
  clock: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.1.4
  auto_route_generator: ^3.0.1
  json_serializable: ^6.1.3
  freezed: ^0.15.0+1

  # Mocking and Testing
  mocktail: ^0.2.0
  bloc_test: ^9.0.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800

    - family: FarmhubIcons
      fonts:
        - asset: assets/fonts/FarmhubIcons.ttf
