name: farmhub
description: A new Flutter project.
version: 0.3.0

publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  auto_route: ^5.0.4

  # Firebase Suite
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  google_sign_in: ^5.3.3

  # Functional Programming
  fpdart: ^0.4.0

  # Value Equality
  equatable: ^2.0.3
  freezed_annotation:

  # Business Logic and Dependency Injection
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  hydrated_bloc: ^9.0.0
  get_it: ^7.2.0

  # Local Storage
  shared_preferences: ^2.0.15

  # Data and Internet
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.5.0

  # Render
  flutter_svg: ^1.1.1+1
  simple_animations: ^5.0.0+3
  bottom_nav_layout: ^3.0.9
  google_nav_bar: ^5.0.6
  syncfusion_flutter_charts: ^20.2.36
  sprung: ^3.0.0
  tab_indicator_styler: ^2.0.0
  dropdown_button2: ^1.6.3
  ndialog: ^4.1.1+1
  flutter_speed_dial: ^6.0.0
  toggle_switch: ^2.0.1
  flutter_styled_toast: ^2.1.3

  # Misc
  lint: ^2.0.1
  path_provider: ^2.0.11
  intl: ^0.17.0
  clock: ^1.1.0
  phone_numbers_parser: ^7.0.0+1
  english_words: ^4.0.0
  package_info_plus: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.1.11
  auto_route_generator: ^5.0.2
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1

  # Mocking and Testing
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

  flutter_lints: ^2.0.1
  logger: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.5

flutter_icons:
  image_path: "assets/images/farmhub_icon.png"
  #image_path_android: "insert path"
  #image_path_ios: "insert path"
  android: true
  adaptive_icon_background: "#F2FFF6"
  adaptive_icon_foreground: "assets/images/farmhub_icon_foreground.png"
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F2FFF6"
  image: assets/images/farmhub_icon_transparent.png

  android_12:
    image: assets/images/farmhub_icon_transparent.png
    icon_background_color: "#F2FFF6"

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/farmhub-logo.svg
    - assets/images/svg/farmhub-start-character.svg
    - assets/images/svg/flowah-minimal-transparent.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800

    - family: FarmhubIcons
      fonts:
        - asset: assets/fonts/FarmhubIcons.ttf
