/// Flutter icons FarmhubIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FarmhubIcons
///      fonts:
///       - asset: fonts/FarmhubIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FarmhubIcons {
  FarmhubIcons._();

  static const _kFontFam = 'FarmhubIcons';
  static const String? _kFontPkg = null;

  static const IconData farmhub_question_mark_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farmhub_shield_search_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farmhub_corn_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farmhub_password_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
