// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_9XpmOV5rlYeE6_kkWtqrDKFNK3GX4t8',
    appId: '1:402773896503:web:2acd80e212a53e106a3eb2',
    messagingSenderId: '402773896503',
    projectId: 'farmhub-23c2b',
    authDomain: 'farmhub-23c2b.firebaseapp.com',
    databaseURL: 'https://farmhub-23c2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmhub-23c2b.appspot.com',
    measurementId: 'G-0PNMCRXLC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC2C5aPMzjJjnGAAMinytamna_ee6HsMU',
    appId: '1:402773896503:android:c85621302579bdd66a3eb2',
    messagingSenderId: '402773896503',
    projectId: 'farmhub-23c2b',
    databaseURL: 'https://farmhub-23c2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmhub-23c2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAytYM2msyc_i0RGe4c3cVPPOfEj0QDBz8',
    appId: '1:402773896503:ios:123413d7bf0da2256a3eb2',
    messagingSenderId: '402773896503',
    projectId: 'farmhub-23c2b',
    databaseURL: 'https://farmhub-23c2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmhub-23c2b.appspot.com',
    androidClientId: '402773896503-7j0onr3hd7sv97mfq843ugbculjvcpvq.apps.googleusercontent.com',
    iosClientId: '402773896503-46ccalimkquj4jumg4qopkj9626jpiic.apps.googleusercontent.com',
    iosBundleId: 'com.farmhub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAytYM2msyc_i0RGe4c3cVPPOfEj0QDBz8',
    appId: '1:402773896503:ios:915b9e9247c0a7316a3eb2',
    messagingSenderId: '402773896503',
    projectId: 'farmhub-23c2b',
    databaseURL: 'https://farmhub-23c2b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmhub-23c2b.appspot.com',
    androidClientId: '402773896503-7j0onr3hd7sv97mfq843ugbculjvcpvq.apps.googleusercontent.com',
    iosClientId: '402773896503-8b0voi72ffoopsoihkaprne8j49t5h2p.apps.googleusercontent.com',
    iosBundleId: 'com.farmhub.farmhub',
  );
}
